version: 1.0.{build}

image: Ubuntu2204

init:
  - echo "Starting AppVeyor build..."

install:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-pip
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements.txt

build_script:
  - chmod +x ranbal
  - chmod +x megoxer
  - python3 shubham.py

artifacts:
  - path: output/*
    name: BuildArtifacts
